version: '3.2'
volumes: 
  postgres-data:
services:
  db:
    image: postgres
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" #TODO for debug only
    environment: 
      - POSTGRES_USER=inspector
      - POSTGRES_PASSWORD=inspector #TODO Remove into .env file !

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: foreman start -f Procfile.dev -p 3000
    volumes:
      - .:/project
      - type: tmpfs
        target: /project/tmp/pids/
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - db